name: Build and Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build_test_job:
    name: 'Build and test job'
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [windows-latest, ubuntu-latest]
    steps:

    - name: 'Checking out repo code'
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Set Node.js 24.x for GitHub Action
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version: 24.x

    - name: 'Validate build'
      run: |
        npm install
        npm run build

    - name: 'Run L0 tests'
      run: |
        npm run test
